name = "seokhyun93-github-io"
main = "worker.js"
compatibility_date = "2025-06-01"
keep_vars = true

[assets]
directory = "./"
binding = "ASSETS"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "shop-images"

[[d1_databases]]
binding = "DB"
database_name = "shop"
database_id = "e6f429eb-ba22-4021-af73-fc6673c44c48"

[triggers]
crons = ["0 0 * * *"]
